### ISSUE TITLE
organism id information storage from stock detail page and in organism table

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1038]
when modifying the species (ex: here from "Manihot esculenta" to "Manihot esculenta subsp. flabellifolia")  type of a given accession it gets stored in the "genus" field  as "subspecies" 
Is this expected? _flabellifolia_ is a subspecies of _Manihot esculenta_ but having it define as "Manihot" would make more sense.

cxgn_cassava=# select stock_id, organism_id, type_id, genus, species,name from stock join organism using(organism_id) where name ilike '%flabellifolia%';
 stock_id | organism_id | type_id |   genus    |                species                 |         name         
----------+-------------+---------+------------+----------------------------------------+----------------------
   610873 |           5 |   76392 | Manihot    | Manihot esculenta                      | M-FLABELLIFOLIA-4127
   610874 |           5 |   76392 | Manihot    | Manihot esculenta                      | M-FLABELLIFOLIA-4139
   610840 |       90019 |   76392 | subspecies | Manihot esculenta subsp. flabellifolia | M. flabellifolia

Moreover  a large set of entries (>14 000) contain the "subspecies" value but they are actually Manihot esculenta, these belong to various experiments not sure why they are differently classified

**Comment by nmenda** [comment]
@bauchetg the species info is already pre-populated in the organism table. You cannot store new organism info from the web interface because it would break the phylogeny tree and the relationships between organisms. 
We update the organism table (and the related phylotree tables) from NCBI taxonomy using the script from the GMOD repo . What you see is what should be there for subspecies. The organism table is used for storing entire phylogenies, so the genus field has an actual genus name only for entries that are of taxa 'species' . Other taxa use the genus field for storing the taxa name

**Comment by bauchetg** [comment]
Clarified by Naama @nmenda.
For information, most of cultivated cassava accession are set as _Manihot esculenta_ species and a substantial subset (>4000 accessions ) are set as _Manihot esculenta subsp. esculenta_ which can be confusing.
