### ISSUE TITLE
Need for treatment level in design types available

### ISSUE THREAD

**Issue by aafolabi** [solgenomics/sgn#1126]
An example is the flowering experiment (RCBD) from NaCRRI with treatment level of "temperature".

**Comment by bauchetg** [comment]
see #299 and #950

**Comment by aco46** [comment]
Jolien from CIP Ghana, have also requested for a trial design with more than one treatment levels.

**Comment by nickmorales** [comment]
when uploading a spreadsheet there could be additional columns that link specific plots/plants to treatments. im not sure if the Add a trial interface could handle this because the treatment needs to be attached to specific plots/plants, instead it could be a step after the Add a trial step where they pick plots/plants (maybe through the fieldmap) and apply treatments to them.

in the database the treatment could be stored as a project of type treatment with the different plant/plots linked to it.

**Comment by nickmorales** [comment]
#1266
