### ISSUE TITLE
wizard search doesnt display trait associated to trials

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1196]
On musabase-test we can not retrieve traits associated to trials.
Wizard was refreshed.

**Comment by bauchetg** [comment]
error is linked to trait query it seems:

11:19:30 2017
No of lines retrieved: 0
Construct Pheno Matrix Start:Wed Aug  2 11:19:30 2017
Construct Pheno Matrix End:Wed Aug  2 11:19:30 2017
Validating criteria_list
Validating query types
criteria_list=$VAR_DUMP1 = [
               'traits'
             ];
dataref=$VAR_DUMP1 = {};
queryref=$VAR_DUMP1 = {};
target_table=traits
QUERY: SELECT trait_id, trait_name FROM public.traits WHERE trait_id IS NOT NULL ORDER BY 2
RESULTS: $VAR_DUMP1 = {
               'results' => []
             };

Could that be due to the addition of postcomposing?

**Comment by bellerbrock** [comment]
Hey @bauchetg , thanks for pointing this out. 
It looks like we ran the appropriate patches on musa-test when we implemented postcomposing, but didn't load any of the new component ontologies or run the load_composed_cvprops.pl script. So the traits view ended up empty because it now identifies the trait_ontology for each database by looking for the cv with the correct cvprop.

I ran `perl bin/load_composed_cvprops.pl -H db4.sgn.cornell.edu -D sandbox_musabase  -T BananaTrait -c composed_trait` to add the right props for the exisiting trait and composed trait ontologies. The same script should be run again if/when component ontologies are loaded.

**Comment by bellerbrock** [comment]
for loading ontologies themselves: `Chado/chado/bin/gmod_load_cvterms.pl`
for example, we've loaded the generic time ontology as: `perl load_cvterms.pl -H db4.sgn.cornell.edu -D sandbox_musabase -s TIME -n cxgn_time_ontology -u -v file.obo`
