### ISSUE TITLE
more precise creation of plant entries

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1235]
right now the only way to create plant entries is to create a uniform number of entries for all plots, but some experiments take a stand count per plot before doing plant phenotyping. we could use this stand count to create the exact number of plant entries in the database, so that they won't need to skip through unneeded plant entries on the fieldbook when doing plant level phenotyping

**Comment by bauchetg** [comment]
@nickmorales:  in trials with a statistical designs, plot size may remain uniform, in the case where there is a shortage of seeds/stacks the remaining plant entries are usually filed by some "fill accession". 
Up to now think we encouraged user to use the "Blank" term, which is not optimal as it is stored as a regular accession. 
Instead of  adjusting plot size to actual number of plant available, we would rather create a "Blank" or "Fill"  experiment prop  that could be ignored from Fieldbook template creation if the user wish too. 
I would certainly not alter the plot size in trials with a design as it would affect the plot physical distribution and subsequent analysis.

**Comment by bauchetg** [comment]
option discussed to allow (or not) tracking of plant position within plot:
-move plant creation to trial creation dialog as an optional info field.
-leave a "post trial creation" option of  plant creation on trial page which could be populated using the trait number of plant stands. This option suppose there is no gap filling done after planting to avoid confusion between evaluated plants and gap filling one.

**Comment by nickmorales** [comment]
will add a button next to the "create plant entry" button that allows user to upload a file with their own plant names
