### ISSUE TITLE
additional customizable columns for fieldbook layout download

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1271]
Current fieldbook layout download has the following fields: 
plot_id | range | plot | rep | accession | is_a_control

Some of these names are confusing - plot_id is really plot name, plot is really plot number, and I'm not sure what range is . . . block maybe?

Breeders using the fieldbook at NCSU are reporting that the option to include trial name, location, year, row/col ( aka tier), pedigree, and even a column summarizing an accession's past performance for important traits would be useful.

**Comment by nickmorales** [comment]
The latest Fieldbook layout now has these fields because those terms were confusing:
'plot_name', 'block_number', 'plot_number', 'rep_number', 'row_number', 'col_number', 'accession_name', 'is_a_control'

What's important about the fieldbook phenotype upload is that the first column is "plot_id" or "plot_name" or "plant_name" or "subplot_name". And that there is a column called "value" and "trait" and "timestamp" somewhere in the exported "database format" fieldbook file. That means we can add as many columns as we want into the layout file and the upload should still work fine.

**Comment by bauchetg** [comment]
see #898
