### ISSUE TITLE
saving all search accession query outputs in a single list

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1296]
In "Search", "Accessions":
Previously we found difficult to create a list containing the entire search output for an accession query. The best patch was to allow a display of a 1000 accessions at once.
In "Search", "Cross":
It turns that the cross search page does this well, 
@titima15 How did you do it ? Would be nice to adopt this approach in other searches like the accession one.

**Comment by titima15** [comment]
Because the tables use dataTable, just change the number of rows on each page.

**Comment by nickmorales** [comment]
this is because the stock search uses server side paging and the cross search uses browser side paging. the number of results on the stock search would be really slow to do through browser paging (>100000). the difference is that with server side paging only the specified number of results are sent to the browser at any one time (10,20,100,etc) and with browser side paging all the results are sent to the browser at once. would a good solution be to add an "All" to the stock search page size? this could be dangerous though because trying to get all 100000 results at once will be very slow.

**Comment by nickmorales** [comment]
@bauchetg can now view 5000 and the search should be a bit faster

**Comment by bauchetg** [comment]
@nickmorales Thanks! The implemented "5000" solution works just fine and solve the problem. Adding a "All" would be ideal but may take too long.
