### ISSUE TITLE
wizard: search filter

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1333]
it would be nice to add some filter/search feature for the wizard, instead of just scrolling to find an item (e.g. trial) in the long list.

**Comment by dauglyon** [comment]
Possibly use column datatable in place of the HTML select

**Comment by bellerbrock** [comment]
@dauglyon I made a rough implementation using datatables in topic/improve_wizard_selects, then put it on hold because I think it makes an already complex interface too confusing

I just stumbled on [this nicely implemented interface](http://www.fao.org/faostat/en/#data/QC) at the FAO though. From what I can tell it uses bootstrap and [faostat-ui-download-selector](https://github.com/FAOSTAT/faostat-ui-download-selector) 
What do you think? Would it make sense to try and use this instead?

**Comment by dauglyon** [comment]
@bellerbrock that looks like it has a lot of extraneous dependencies. Also requires templating systems that we don't use. Maybe it'd be a good place to start though. In theory, this might also be a good place to use D3. But I definitely like the design of it

**Comment by dauglyon** [comment]
By "that" I mean the one you linked to. I haven't seen the branch yet. Perhaps some of the clutter can be solved with css?

**Comment by bellerbrock** [comment]
@dauglyon agreed, probably smarter to borrow the general design ideas but not a bunch of extra dependencies. And yeah, I haven't considered the CSS approach because I'm less familiar with it, but maybe it's about time I changed that. Got any good examples to point me to?

**Comment by bellerbrock** [comment]
Added by @dauglyon in #2351
