### ISSUE TITLE
phenotyping spreadsheet upload has undocumented requirements

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1373]
Expected Behavior 
--------------------------------------------------------------------------
Upload phenotyping spreadsheet file format info doesn't mention these requirements, but upload fails if design params are missing or data columns are in the wrong order.

Also, it is confusing that the error messages persist and the upload is disabled after closing and reopening the modal.

For Bugs:
---------

**Comment by lukasmueller** [comment]
An improved generic error message (and potentially contact info for help) may be good.

**Comment by bellerbrock** [comment]
Ok, I've taken a closer look at this as the NCSU program is now trying to upload lots of yield trial data. The issue is not just that the upload requirements aren't documented, but that they prevent a streamlined workflow.

For example, the desired workflow is to be able to upload a single large spreadsheet with data from multiple yield trials. Plot name in the first column, trait measurements in the rest. This format is consistent with the documentation, but then the upload expects a header with design info for a single trial, as well as additional columns like accession name and plot number. 

Rather than add those requirements to the docs, the users here at least would prefer to remove them. @lukasmueller @nmenda @nickmorales What do you think? Is there a good reason I'm missing that we want to require the design info and columns to be in the upload file?

**Comment by nickmorales** [comment]
@bellerbrock you can create a phenotyping spreadsheet for multiple trials on the database, and then it is just a matter of filling in the values and uploading the file. it is important to create the spreadsheet from the database, so that they have exactly the right plot/plant names and the right trait IDs.

we can define a new upload format, called "simple" or something like that which just has a column for the observationunit_name and columns for traits if that helps. during phenotype spreadsheet creation and upload, there would be an option to select "Simple" or "Detailed" for the spreadsheet format.

of course documentation is an issue and the "Managing Phenotypic Data" section needs work (i wrote it poorly) http://solgenomics.github.io/sgn/03_managing_breeding_data/03_09.html

**Comment by bellerbrock** [comment]
@nickmorales Ah ok, I think part of the problem is that sweetpotatobase is missing some updates, I see the option to create a spreadsheet for multiple trials now, but only on the other sites. Is there a site update planned for this week?

And yes a simple format would be very useful. Many phenotypes are generated outside of the fieldbook format, for example NIRS measurements and data from an exeter grading machine. The measurements are still attached to valid plot names through scanning barcodes, but they will be a fairly random mix, say all of the rep 1 plots from 5 different trials. It will be much simpler to upload that data as is rather than try to reconstruct a template through the database.
