### ISSUE TITLE
Edit trial detail privilege 

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1391]
Expected Behavior 
--------------------------------------------------------------------------
While editing trial details on trial detail page, it gives an error indicating that a curator or submitter associated with a breeding program has no privilege to edit the trial.

For Bugs:
---------

**Comment by bellerbrock** [comment]
Hey Nick, are there specific steps to reproduce this? I haven't been able to reproduce it with janedoe and johndoe editing trial details in the fixture.

**Comment by nickmorales** [comment]
Its happening on this trial https://yambase.org/breeders/trial/143?format=

**Comment by bellerbrock** [comment]
Ok, turns out this is a whitespace issue. The 'CSIR SARI' name had a space at the end in the project table but not in the role table
![screenshot from 2018-01-22 18-44-15](https://user-images.githubusercontent.com/11297346/35250472-cb4ab48e-ffa4-11e7-9c9a-ab98c3327ee2.png)

I've removed the whitespace in cxgn_yambase which fixes this specific instance. To prevent similiar problems in the future we might want to:

- trim leading/trailing whitespace from breeding program names when they're added
- make breeding program's editable through the web interface
- find a way to avoid the denormalization of names between breeding programs in sgn_people.sp_roles and the project table.
