### ISSUE TITLE
Wizard trial queries show discrepancies

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1457]
Expected Behavior 
--------------------------------------------------------------------------
@bellerbrock 
We find discrepancies between wizard "trial" query (2168 trials)  and "breeding program", "trial query" (2023 trials) 145 trials do not match among, even if they do have a breeding program assigned, below more details.

-CIAT (101 trials, assigned to CIAT breeding program, +1 to delete)
-NRCRI (25 trials, all "genotyping trials", seems the main query does not consider trial types difference, but the breeding program one does)
-NACRRI ( 10 trials, assigned to NACRRI breeding program, 6 to be deleted)
-ARI (3 trials, assigned to ARI breeding program, 1 to be deleted?)
-IITA (4 trials, assigned to NACRRI breeding program, 2 to be deleted)

Enclosed the details about these
[wizard_145_trials.txt](https://github.com/solgenomics/sgn/files/1475518/wizard_145_trials.txt)

Similarly, the "Search", "Trials" list show 19 trials without breeding programs assigned
[search_19_trials_without_breeding_program.txt](https://github.com/solgenomics/sgn/files/1475517/search_19_trials_without_breeding_program.txt)

@rachealmukisa, @pvnsprasad could you check among these two files which trials needs to be deleted? Could you correspond with colleagues from ARI and NRCRI respectively?

For Bugs:
---------

### Enviroment 

cassavabase.org

**Comment by pvnsprasad** [comment]
@bauchetg I have re uploaded the two trials 07uyt23ICT1Abj and 07uyt30sgIB from IITA breeding program as earlier ones did not have proper layout or trait data

**Comment by bauchetg** [comment]
Deleted 07uyt23ICT1Abj_old and 07uyt30sgIB_old let me know about others.

**Comment by bellerbrock** [comment]
@bauchetg Hey Guillaume, sorry for not getting to this earlier. The difference you're seeing is due to different underlying queries. Requesting "trials"  in the first panel get all the trials in the project table. Choosing "breeding_programs", then "trials" uses the materialized_phenoview, which ignores trials that don't have plots and accessions connected to them through nd_experiment.

How would you want these queries to change? Should all trials show up, regardless of their completeness? That would be simple to implement. Or should the first query ignore trials that are missing key elements too?

**Comment by bauchetg** [comment]
Thanks Bryan, no worries. Showing all trials would probably make more sense.
Having the ability of selecting trials according to their level of completeness would be very useful for further data analysis or dataset building. This aspect of trial completness is also mentioned in #1416
