### ISSUE TITLE
trial/breeding program attribution in trial folder conflict 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1463]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Some new trials created with a defined breeding program loose program affiliation when moved to folder.
### Enviroment 

cassavabase.org
#### Steps to Reproduce

(ex: https://cassavabase.org/folder/3376)
trials loose their breeding program affiliation once sent to a given folder (ex folder "04_llesa" and trial "04multloc15cmdILSset3"): "No Breeding Program".
Once in folder, user is unable to reset the breeding program: "You need to be associated with breeding program to change the details of this trial" (even if user has updated  IITA role).

If trial is moved out from folder it recovers its original breeding program.
This does not occur for every folder, example given is a new folder.
Previously fixed the issue by changing breeding program assignation to a different and then back to desired one but could not reproduce the fix.
Overall an additional "super user" role (affiliated to all breeding programs would be useful)

Something to do with lib/SGN/Controller/AJAX/TrialMetadata.pm  and function "sub trial_details_POST " l.133-173

**Comment by nickmorales** [comment]
occurs when editing a trial's info, if the user changes the breeding program to one that is different from the breeding program that the folder is part of, things get messed up. 

this can easily occur unintentionally because when editing a trial's details the form automatically selects IITA. so to fix this, i think it makes sense to restrict the user from changing a trial's breeding program if the trial is already in a folder.
