### ISSUE TITLE
AddSeedlotViews patch not working

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1618]
Expected Behavior 
--------------------------------------------------------------------------

When i run patch 00086 AddSeedlotViews on cxgn_nelsonlab (which i moved to db3) it gives me 
ERROR:  more than one row returned by a subquery used as an expression at AddSeedlotViews.pm line 50
Does this view take into account that there can be more than one seedlot per accession?

For Bugs:
---------

**Comment by bellerbrock** [comment]
Hey @nickmorales , errors like this have occurred before in other dbs, caused by duplicate cvterms. I'd guess that one of the subqueries used to retrieve type ids , for example  ```seedlot.type_id IN (SELECT cvterm_id from cvterm where cvterm.name = 'seedlot')``` is returning multiple ids.

If you want to check, the possible culprits are:
'seedlot',
'breeding_program_trial_relationship', 
'project year',
'accession',
'breeding_program'
'plant',
'plot',
'trait_ontology',
'composed_trait_ontology',
'collection_of',
'seedlot_experiment',
'design',
'project_type'

It also may be better to change the patch so that it also filters by cv_id in the subqueries (if duplicate names are allowed as long as they are in different cvs).

**Comment by nickmorales** [comment]
thanks @bellerbrock there were duplicated 'trait_ontology' and 'composed_trait_ontology' terms

**Comment by nickmorales** [comment]
another one that gave me issue was 'VARIABLE_OF'
