### ISSUE TITLE
pedigree viewer female/male parentage display is reversed

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1644]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Pedigree display convention set the female parent to the left and the male parent to the right of the progeny, as in the pedigree string writing.

#### Steps to Reproduce

as in: https://musabase-test.sgn.cornell.edu/stock/65549/view
<img width="262" alt="screen shot 2018-02-26 at 7 27 25 pm" src="https://user-images.githubusercontent.com/12039071/36682020-29441e1c-1b2b-11e8-9bfd-953a47e6e0aa.png">

917K-2 should be on the lelft hand side and 9128-3 to the right

**Comment by dauglyon** [comment]
The algorithm used to lay out nodes is not going to be able to untangle them if we also force order, so mother/father relationships are instead shown as red/blue

**Comment by bauchetg** [comment]
Thanks @dauglyon this is too bad as the view is kind of contradictory with pedigree string.
Would switching the way the input data is taken be of any help?

**Comment by dauglyon** [comment]
@bauchetg,

@titima15 and I discussed this and came up with a possible half-way solution which would be to put the male/female symbol along with the color

**Comment by bauchetg** [comment]
@dauglyon thanks, the matter from breeders is more on the standards of pedigree display (female first) rather than a mis-interpretation of the current color code (which is quite clear to them).
But adding the symbols is probably good! Thanks again.

**Comment by dauglyon** [comment]
So, the current version (see #1682), does try to keep parents in order (brapi parent1/parent2 which is mother/father), however it strongly prioritizes have an untangled and visually compact tree. Here is an example of what it looks like when the order is _not_ maintained
<img width="1336" alt="screen shot 2018-03-07 at 11 47 54 am" src="https://user-images.githubusercontent.com/5115845/37105907-60245f80-21fe-11e8-9cac-7722bcd2ebe9.png">
You can kind of see how it the three things we want (compactness, untangledness, and order) start to interfere with eachother. However, the new version _should_ fix trees showing only three accessions (mother,father,child) so that they are ordered correctly.

**Comment by bauchetg** [comment]
That is the best compromise! Thanks Dave.
