### ISSUE TITLE
pedigree tree problem on test-site

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1647]
Expected Behavior 
--------------------------------------------------------------------------

Some people saw problem with pedigree viewer on test site on page like https://musabase-test.sgn.cornell.edu/stock/65549/view 

I think its caused by HTTP authentication on the test sites not being used in the pedigree tree URL calls?

For Bugs:
---------

**Comment by dauglyon** [comment]
I can't reproduce the issue unfortunately. Is there more information on what went wrong?

**Comment by nickmorales** [comment]
i can't reproduce it either but its happening on https://musabase-test.sgn.cornell.edu/stock/65558/view on chrome on a windows machine

**Comment by dauglyon** [comment]
I just managed to reproduce this on my system from the link in #1671 

I'm not sure why the credentials aren't being sent with the ajax request, I am switching the API which is used to fetch files in the new pedigree viewer version, so hopefully this issue will resolve itself. I will keep an eye out in case it does not.

**Comment by dauglyon** [comment]
So, the current version (see #1682), does try to keep parents in order (brapi parent1/parent2 which is mother/father), however it strongly prioritizes have an untangled and visually compact tree. Here is an example of what it looks like when the order is _not_ maintained
<img width="1336" alt="screen shot 2018-03-07 at 11 47 54 am" src="https://user-images.githubusercontent.com/5115845/37105907-60245f80-21fe-11e8-9cac-7722bcd2ebe9.png">
You can kind of see how it the three things we want (compactness, untangledness, and order) start to interfere with eachother. However, the new version _should_ fix trees showing only three accessions (mother,father,child) so that they are ordered correctly.

**Comment by nickmorales** [comment]
this is a big problem when it does occur because it just continually keeps asking for authentication https://cassava-test.sgn.cornell.edu/stock/39671/view makes the page basically unusable when it happens

**Comment by dauglyon** [comment]
@nickmorales it should be possible to change the Ajax requests that the tool makes to have them send cookies along with the requests which should solve the issue. I can look at it tomorrow.

**Comment by dauglyon** [comment]
@nickmorales however, I've never seen it ask for auth more than once. And it has a very strange reproducibility pattern. (It doesn't happen at the link you posted for me for example)

**Comment by dauglyon** [comment]
So, I cannot for the life of me figure out what is causing this bug. Could you take a look? this is where requests are happening: 
https://github.com/solgenomics/sgn/pull/1486/files#diff-7960a2e2e801d81384f954b58d7ced36R205
https://github.com/solgenomics/sgn/pull/1486/files#diff-7960a2e2e801d81384f954b58d7ced36R217


@nickmorales

**Comment by nickmorales** [comment]
i cant seem to reproduce this issue again
