### ISSUE TITLE
"Number of fruit" missing in batch upload of crosses

### ISSUE THREAD

**Issue by aafolabi** [solgenomics/sgn#1670]
Expected Behavior 
--------------------------------------------------------------------------

Number of Flowers 
Pollination Date 
Harvest Date 
Number of Seeds Harvested 
Days to Maturity 
Seed Extraction Date 
Number of Seeds Extracted 
Number of Viable Seeds 
Number of Nonviable Seeds 
Days from Harvest to Extraction 

For Bugs:
---------

**Comment by aco46** [comment]
@aafolabi : are they specific to both yam and cassava database?

**Comment by titima15** [comment]
The spreadsheet that I got for yam didn't have number of fruits.  That's why I didn't add for yambase, but it is a very easy fix. 

@aafolabi Could you please check if you need any more cross info for yambase so that we can update at the same time as number of fruits.

@aco46 cassavabase already has number of fruits.

**Comment by titima15** [comment]
@aafolabi Because now we can customize cross info for different databases. For "Date of Bagging" and "Time of Pollination", you want for just yambase, right?  Currently, we have "Number of Bags for cassavabase, but not yambase.  Becasue you are working with both cassavabase and yambase, please specify which database as well.

**Comment by aco46** [comment]
@aafolabi @titima15 I've added Time of Pollination, Date of Bagging and Number of Bags to Yambase test and live site.

**Comment by aafolabi** [comment]
Excellent @aco46 and @titima15 . Thanks
