### ISSUE TITLE
pedigree tree doesnt always display on Chrome

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1671]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
In Chrome some individuals do nto show pedigree data whereas they do on Firefox.
may be related to #1647 ?
### Environment 

cassavabase
#### Steps to Reproduce

https://cassava-test.sgn.cornell.edu/stock/38771/view

**Comment by dauglyon** [comment]
Is this only happening on the test site?


On March 5, 2018 at 11:30:46 AM, Guillaume Bauchet (notifications@github.com)
wrote:

Expected Behavior For Bugs:

In Chrome some individuals do nto show pedigree data whereas they do on
Firefox.
may be related to #1647 <https://github.com/solgenomics/sgn/issues/1647> ?
Environment

cassavabase
Steps to Reproduce

https://cassava-test.sgn.cornell.edu/stock/38771/view

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/solgenomics/sgn/issues/1671>, or mute the thread

**Comment by dauglyon** [comment]
It looks like this is indeed related to #1647, something to do with the HTTP(s) login
