### ISSUE TITLE
Stock type all option in stock search

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1770]
Expected Behavior 
--------------------------------------------------------------------------

Would be useful to have an option in the stock search that searches all stock types. And if it's not very slow it could be a good default option.

It's confusing to enter a valid plot name in the accession and plot search and get no results because stock type 'accession' is selected by default in a collapsed section.

For Bugs:
---------

**Comment by bauchetg** [comment]
Most users have little interest in plots (they get so many after a while):
-Instead of having a by defaults accessions and plot output could filtering options from "properties" be displayed constantly?
-When expending it thi section is a little too large and hide the search output section form the main screen. A more compact version would help too
-"Properties" is actually not intuitive to many maybe "Advance filtering" would be better?
