### ISSUE TITLE
PCA feedback

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1953]
Expected Behavior 
--------------------------------------------------------------------------
@isaak Thanks for making this available, below some (too many ?)suggestions

-1- Stand alone PCA tool:

-a-Data eligibility
Does the  tool solely focuses on SNP data: accession, trial, population related?
Restrict list type display according to list type that can be plotted
Or can it handled any multivariate analysis (ie: on phenotypes), that would be great!

-b-Make more informative message while failing, ex:
<img width="957" alt="screen shot 2018-06-18 at 9 14 00 pm" src="https://user-images.githubusercontent.com/12039071/41570470-001203aa-733d-11e8-9a35-52a480086177.png">
For example, these accessions have actually no molecular data available

There is maybe something else, in the case below molecular data is available but I get an error
<img width="993" alt="screen shot 2018-06-18 at 9 41 55 pm" src="https://user-images.githubusercontent.com/12039071/41571329-afe34eda-7340-11e8-8867-6c2068851d1f.png">

In both case I made the list public so that you can repoduce the errors

-c-If possible (think it is @dauglyon @afpowell may confirm) but there is a D3 pca module which allows user to do a graphical selection of the dots so that you can save them directly in a list (would be extremely useful, when you wish to select a subgroup of individuals after population structure analysis)

-d-Display a summary of what is plotted ave the ability to download or store the eigenvalues 

-2- PCA tool with SolGS
Including the PCA step in a workflow (as we have for trial creation for example) for SolGS would be helpful.

For Bugs:
---------

**Comment by isaak** [comment]
Thanks for the feedback, Guillaume!

At this stage, the tool uses SNP Data. Using phenotypic variables is in the plan.

The stand alone tool works on lists of accessions and trials only; Only such lists show in the tool page. Please let me know if other types list sneaked in in the lists menu.

I suspect when you run the PCA on your examples, cassava-test was on a branch other than the pca branch. Otherwise, i
<img width="1051" alt="pca_17 gs" src="https://user-images.githubusercontent.com/163702/41584643-22d2b20c-73a8-11e8-9320-1fa4e8dd4bd8.png">
f you try to run on accessions with out genotype data, it should show 'There is no genotype data ', I think.  The second example,  is it this one: https://cassava-test.sgn.cornell.edu/pca/analysis/uploaded_5392? Can you try again?

Yes, it would good to add the selection tool and download the eigenvalues... I will take a look for the D3 pca module.

**Comment by bauchetg** [comment]
@isaak, the test population works now, thanks.

**Comment by isaak** [comment]
cool!
