### ISSUE TITLE
Upload Genotypes option

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2049]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

Step 3: "Genotyping protocol" 
Exsiting protocols do not show in the list 

As well, the option:
"Sample Names Include IGD Numbers (e.g. sample_name:IGD1001:09)"

Since different platforms may be usedhould be more like:
"Sample Names were collected with cassavabase using Genotyping trial/tissue ID  (e.g. sample_name:215100019):"
![screen shot 2018-07-25 at 11 02 14 am](https://user-images.githubusercontent.com/12039071/43209266-36d866de-8ffa-11e8-8541-14cccf57b19d.png)

**Comment by nickmorales** [comment]
hi @bauchetg the previously loaded protocols do not show here because they we loaded differently and do not have the description, reference genome, number of marker, etc info. is it feasible to reload the previously loaded genotype info?

the number after the sample name (sample_name:29393939) is created by the genotyping facility, so its not coming from cassavabase, but i agree that the option should be more generic and not specifically IGD

**Comment by bauchetg** [comment]
@nickmorales We can relaod the data
