### ISSUE TITLE
Label designer: include management factor status on labels

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2074]
Expected Behavior 
--------------------------------------------------------------------------

For split plot design, users need to include include treated vs control plots on their labels
Currently this term is not available

For Bugs:
---------

**Comment by nickmorales** [comment]
do you mean make treatments (management factors) available for printing on labels?

**Comment by bauchetg** [comment]
@nickmorales yes that's correct

**Comment by nickmorales** [comment]
@bellerbrock I am updating CXGN::Trial::TrialLayoutDownload to be easier to build on, but it might be a good idea to source information from TrialLayoutDownload, instead of TrialLayout for the label designer. TrialLayoutDownload can return management factors and average phenotype performance info

**Comment by bellerbrock** [comment]
@nickmorales good idea, looks like it can return pedigree too? I've been working on a few requested updates in [topic/label_designer_updates](https://github.com/solgenomics/sgn/tree/topic/label_designer_updates), and can include a switch from TrialLayout to TrialLayoutDownload too.

**Comment by nickmorales** [comment]
@bellerbrock ok good thanks. it can return all the fields listed in the "possible columns" plus any management factors and trait averages specified. it would be ideal if you did not modify any of the internals of TrialLayoutDownload... i am rewriting it so that it is easier to work with, and mainly modifying it so that when you request the plant level layout it will be sorted by plot number and plant index number already.
