### ISSUE TITLE
ANOVA analysis is broken

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2138]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
example trial:
https://cassavabase.org/breeders/trial/4279?format=
While selecting a trait it returns an "undefined" value
<img width="1065" alt="screen shot 2018-08-30 at 9 55 51 am" src="https://user-images.githubusercontent.com/12039071/44856398-49712580-ac3b-11e8-947f-f5c8c6914b7e.png">
@isaak Seems related with the cluster analysis, perhaps file outputs are not rerouted to the trial page?
<img width="1356" alt="screen shot 2018-08-30 at 9 56 43 am" src="https://user-images.githubusercontent.com/12039071/44856456-6c033e80-ac3b-11e8-87ff-7bde77d70eac.png">

**Comment by isaak** [comment]
Partly special characters ( e.g., commas)  in the 'studyDescription' field of the phenotype data are breaking reading data to R.  Even though that is fixed by explicitly defining field separator, something more about the phenotype data structure is still breaking reading it to R. 

What changed recently about the phenotype data structure?

**Comment by nickmorales** [comment]
There were a few new columns in that response, but that was from a while ago
