### ISSUE TITLE
visualize selection index

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2238]

**Comment by bauchetg** [comment]
@Isaak what type of visualization do you have in mind?

**Comment by bauchetg** [comment]
It could be something similar to this:
https://docs.telerik.com/devtools/aspnet-ajax/controls/htmlchart/chart-types/radar-chart
We are discussing this with @dauglyon and @lukasmueller to summarize accession overall performance display. This is display frequently used to give a profile

**Comment by dauglyon** [comment]
If we want to show many values with many traits, it could be better to use a something like [parallel coordinates](https://syntagmatic.github.io/parallel-coordinates/) as it better represents the idea of "clusters" of similar items. IMO radar graphs should only be used for visual barcoding or quick differentiation without an emphasis on the underlying values. [Here is a good article that sums up most of my complaints about radar graphs.](https://blog.scottlogic.com/2011/09/23/a-critique-of-radar-charts.html)

**Comment by bauchetg** [comment]
Nice ref @dauglyon, thanks! As discussed:
-> the scale issue is no longer thre with BLUPs,  BUT these values are less comprehensive to the breeder since there are centered on 0.
-> Commonly in breeding a selection index involves 4-5 traits (rarely more), therefore the number of traits simultaneously is not be the main problem. 
-> The polar coordinates system could be a good compromise (radar plot too biased, parallel coordinates to heavy interpreting)
-> What matters: give a quick snapshot of overall accession performance/profile.

**Comment by isaak** [comment]
#3651
