### ISSUE TITLE
Allow family names (crosses) to be in trial layouts for nursery trials

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2360]
Expected Behavior 
--------------------------------------------------------------------------

As requested by Jolien

For Bugs:
---------

**Comment by bellerbrock** [comment]
This is important. Nursery trials can contain 10s of thousands fo seedlings, so instead of individual genotype names they are tracked in groups by the parent cross names. The most important change is to make it possible to design trials with cross names. After that it would be helpful to specify the plot size based on the number of progeny planted from the cross, and create the field map accordingly - plots will be of varying sizes based on the number of progeny planted

**Comment by bellerbrock** [comment]
related to #1850

**Comment by lukasmueller** [comment]
I think Titima added this so this could be closed?

**Comment by titima15** [comment]
@lukasmueller yes, it's done
