### ISSUE TITLE
yambase blast job submission is broken

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2417]
Expected Behavior 
--------------------------------------------------------------------------
Seems that the blast function is disconnected form cluster jobs.
Runs fine on yam-test
![Screen Shot 2019-04-13 at 11 51 51 AM](https://user-images.githubusercontent.com/12039071/56082156-5bc35c80-5de3-11e9-87dd-768a96264266.png)

For Bugs:
---------

**Comment by lukasmueller** [comment]
Actually, the BLAST problem fixed with pull request #2479 was different, an issue with a javascript library that had not been moved to the new javascript system. It crashed the BLAST page after successful completion of the analysis, not showing the results. This affected all systems, including SGN. Both yambase and SGN have been updated to the new release tag, sgn-249.0 that has this issue fixed.
