### ISSUE TITLE
Printing barcode for specific accessions from a trial at plant level

### ISSUE THREAD

**Issue by mkaranja** [solgenomics/sgn#2572]
Expected Behavior 
--------------------------------------------------------------------------
We may want to generate barcode for some specific accessions from a trial however from the yambase there is no room to select accessions during the process of generating the barcode 

For Bugs:
---------

**Comment by bellerbrock** [comment]
Hi Margaret, if I understand correctly you want to ability to select a subset of the accessions within a trial and make barcoded labels just for them?

That is possible with the current label designer, though maybe a bit tricky to figure out. The key is to make a plot list containing your specific subset, then select it as your data source rather than the whole trial. Let me know if that addresses your use case.

**Comment by mkaranja** [comment]
Thanks Bryan.
Yes that is what we need in yambase. 
I tested that by creating a list of plots for the specific accessions. In the Field dropdown, I can see 'plant_names' but I want 'plant_name' which is not included

**Comment by bellerbrock** [comment]
Ah, I see. You'd like to make barcode labels for each individual plant within your specific subset of the trial. That's an easy feature to enable.

I'm finishing some label designer updates in a branch as we speak. I'll merge it including this feature early next week, if not sooner.

**Comment by mkaranja** [comment]
Cool. Thanks so much!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
