### ISSUE TITLE
Site-specific image handling is confusing

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2734]
Expected Behavior 
--------------------------------------------------------------------------
The current system of site-specific mason living in separate repos, but site-specific images living in sgn/static/documents/img is confusing.

I'm not sure of the best solution. The simplest might be moving the site-specific images to their corresponding site-specific mason repos, but with more refactoring maybe all site-specific customization could accomplished via conf variables? 

For Bugs:
---------

**Comment by lukasmueller** [comment]
The images cannot be stored in the mason files I think, because it is outside of the repo and Catalyst doesn't like to serve those files. The best way to deal with site specific images, as should be done with most images, is to store them in the database. There are handy mason modules for displaying images from the database directly. What do you think?
