### ISSUE TITLE
Link to jbrowse from marker detail pages is not available anymore since redesign

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#297]
As reported by Martha Mutschler

**Comment by lukasmueller** [comment]
Are all the markers shown on tomato by default? (there are lots of pepper or eggplant markers as well...)

**Comment by bellerbrock** [comment]
They are - I don't think there is an eggplant jbrowse, or that the pepper jbrowse has marker tracks. Is that something we could change?



—

**Comment by lukasmueller** [comment]
Yes, we should probably add marker tracks to the other genomes… but later.

**Comment by bellerbrock** [comment]
Ok. I just updated the fix to use existing iframe code rather than a link.
If someone points me to the relevant files I'd be happy to work on the
pepper and eggplant jbrowse!

In order to deal with linking to multiple jbrowse sources, noe and I
discussed the possibility of storing the jbrowse source for each species as
a variable in the conf file. Does that solution make sense?

On 20 November 2015 at 03:19, Lukas Mueller <notifications@github.com>
wrote:

> Yes, we should probably add marker tracks to the other genomes… but later.
> > On Nov 19, 2015, at 10:12 PM, Bryan Ellerbrock <notifications@github.com>
> wrote:
> >
> > They are - I don't think there is an eggplant jbrowse, or that the
> pepper jbrowse has marker tracks. Is that something we could change?
> >
> >
> >
> > —
> > Sent from Mailbox
> >
> > On Thu, Nov 19, 2015 at 8:24 PM, Lukas Mueller <notifications@github.com>
>
> > wrote:
> >
> > > Are all the markers shown on tomato by default? (there are lots of
> pepper or eggplant markers as well...)
> > > ---
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/solgenomics/sgn/issues/297#issuecomment-158251175
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solgenomics/sgn/issues/297#issuecomment-158267535>.
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868
