### ISSUE TITLE
Replace Phenotype Observations with NULL

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3017]
Expected Behavior 
--------------------------------------------------------------------------

When uploading a phenotyping spreadsheet, if there is already a value stored for that trait and stock the verification step will give the user the option to overwrite the previously stored value with the new one.

![image](https://user-images.githubusercontent.com/7526014/88563080-8567bd80-cfff-11ea-91a6-a9193847b8c5.png)

However, is there a way to set an existing value to null or to remove the value?  When uploading a phenotyping spreadsheet with empty values for a trait, the verification screen does not prompt the user to overwrite the previously stored value and storing the file does not modify the values.

![image](https://user-images.githubusercontent.com/7526014/88562907-4afe2080-cfff-11ea-9890-cf64fae141ec.png)

One use case for this scenario is that a breeder has identified outliers after the original data has been stored in the database and would like the outliers to be removed.

For Bugs:
---------

**Comment by ch728** [comment]
I've tried to do this as well. You can always delete the data associated with the field trial and then re-upload your data sheet with only the observations you want. If you want to suppress outliers, there is an option on the trial page to suppress. You have to go to "Field Layout Tools and Phenotype Heatmap" and choose a trait, you can then click on a specific plot and suppress the observation. It would be nice if there was a way of doing the in bulk through an upload or list instead of clicking on one plot at a time.

**Comment by lukasmueller** [comment]
Add another checkbox "overwrite existing data with empty values" in the upload as an additional option.

**Comment by dwaring87** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replacing Phenotype Observations with NULL](https://trello.com/c/Q3Gcxfcv/13-replacing-phenotype-observations-with-null)
