### ISSUE TITLE
Multi trial upload fails sometimes

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3231]
Expected Behavior 
--------------------------------------------------------------------------
Seems to be a database problem, as some databases work and some don't.

For Bugs:
---------

**Comment by bellerbrock** [comment]
@lukasmueller @nmenda One possible cause of multi-trial upload problems is an unsorted upload file. The file format explanation doesn't mention it, but the database expects the upload file to be sorted by trial name so that all the plots in a given trial are grouped together. I just noticed this today when an unsorted multi-trial file loaded into spbase finished without error but resulted in incomplete trial designs.

Not sure which is the better fix, but we should either add a warning to the file format info or have the upload code do a sort itself before processing.

**Comment by lukasmueller** [comment]
Probably should be sorted on the backend :-)

**Comment by nmenda** [comment]
#3283 should fix this
I don't know how the multi trial loaded was working previously since  it was checking stock name uniqueness on  row numbers instead of plot names

**Comment by nmenda** [comment]
this trial in cassvabase was causing the loader to fail 
https://cassavabase.org/breeders/trial/7728

It has numbers from 1- 72 as the plot names
