### ISSUE TITLE
Generated file from BreedBase for Field Book can include illegal characters

### ISSUE THREAD

**Issue by trife** [solgenomics/sgn#3375]
Expected Behavior
--------------------------------------------------------------------------

Output file should not include slashes, parentheses, or special characters in headers of generated field files.

Reported by Jessica Rutkoski's group.

**Comment by dwaring87** [comment]
@trife What characters does Field Book support?  Would it be possible for Field Book to support additional characters?  As of now, T3's trait names include dashes and slashes since we add the scale name to the trait.  I imagine if those characters were removed then the upload back into breedbase would have issues.

**Comment by lukasmueller** [comment]
Breedbase only matches on the ID of the trait, so trait names with strange characters such as slashes could have them replaced by underlines before export. Please TEST first!!!

**Comment by trife** [comment]
We originally had some issues supporting special characters in Field Book due to poor database design. Chaney has done quite a bit of work to update the database so I'll do some testing to see if those special character catches are still necessary and report back.

**Comment by lukasmueller** [comment]
Make sure your database is UTF-8 encoded...
________________________________

**Comment by dwaring87** [comment]
> Breedbase only matches on the ID of the trait, so trait names with strange characters such as slashes could have them replaced by underlines before export. Please TEST first!!!

I tested this and it is true - the trait names don't need to match the names in the database as long as the CO identifier is present.

That means breedbase could remove any special characters from column headers for traits and the upload of the file from Field Book back to breedbase should still work.  However, I think it would be better if Field Book could support the special characters, if possible.  This way the trait names are consistent between the two platforms.  Also, I'm not sure if this problem is solely due to trait names.  There may be other column headers with special characters that replacement may cause other downstream issues?

**Comment by trife** [comment]
Just did some testing and while it looks like we've made a little progress in handling special characters there are still a few issues and so this likely won't be changed within Field Book until after the next release. Making an issue to track this on our side: https://github.com/PhenoApps/Field-Book/issues/229
