### ISSUE TITLE
trait ontology detail page does not display informations correctly

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#346]
Page shows typos and display issues in synonyms:

<img width="1672" alt="screen shot 2015-12-10 at 12 16 53 pm" src="https://cloud.githubusercontent.com/assets/12039071/11722717/52889fbc-9f38-11e5-9941-81aa38cd6f34.png">
ex: https://cassavabase.org/chado/cvterm?action=view&cvterm_id=70722

**Comment by lukasmueller** [comment]
Other issues with the page: 

Annotated loci and Annotated stocks sections are always empty in Cassavabase  (but not in SGN). Hide empty sections!

Add a section "Trait assayed in trials", also hide it if empty (so that it doesn't show on SGN)

**Comment by nmenda** [comment]
adfda6cf282f0ab352778ecab7ef0fe617984b63

**Comment by nickmorales** [comment]
the "phenotyping trials" section works, but the "annotated stocks" and "phenotyped accessions" sections do not show
![image](https://user-images.githubusercontent.com/7028512/34881412-82fa3270-f781-11e7-9ff3-48c32b3f71f2.png)

**Comment by nmenda** [comment]
this is a bit confusing, the 'annotated stocks' is only for stocks that have ontology annotations - these come from stock_dbxref, so except for sgn, none of the other databases have those currently

'Phenotyped accessions' should fetch the child stocks (plants, plots, etc.) because no accession should really have a direct phenotype in nd_experiment_stock, it all comes from derived stocks because we phenotype plots and accessions.
