### ISSUE TITLE
upload fieldbook file

### ISSUE THREAD

**Issue by barriball** [solgenomics/sgn#3820]
Expected Behavior 
--------------------------------------------------------------------------

Upload fieldbook file: When verifying the fieldbook file the popup window gives a "File has no header row" error when file clearly is an unedited version of the autogenerated fieldbook file downloaded from breedbase project.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Could you send me an example file?

**Comment by barriball** [comment]
[2021-11-17-01-15-05_Copy of fieldbook_layout_2021-11-17_15 55 07_testmoc_table.csv](https://github.com/solgenomics/sgn/files/7571516/2021-11-17-01-15-05_Copy.of.fieldbook_layout_2021-11-17_15.55.07_testmoc_table.csv)

**Comment by lukasmueller** [comment]
Hi Spencer, could you let me know how exactly you generated the file (page url etc) and which upload function you are using?

**Comment by lukasmueller** [comment]
Hmmm... I think I see what is going on. This file has these pesky DOS style line endings and that's what causes trouble in this case I think. DOS files (as produced by Windows have two characters marking an end of line, \n\r . 

I am preparing a patch that filters out the line ending "\r" character. This has been an issue in some of our uploads in the past. I think this one hasn't been caught because it normally comes out of fieldbook correctly, but if you open the file on a Windows machine it will add the return (\r) character at the end. (UNIX systems, including UNIX-based Macs, only have a \n character at the end of the line)

**Comment by lukasmueller** [comment]
I think this may have been fixed via e71d89de8778b3765d2d484ddaa918679f4e75e8.
