### ISSUE TITLE
Field Layout Does Not Load (for new trials)

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3960]
Expected Behavior 
--------------------------------------------------------------------------

When expanding the Field Layout Map on a trial detail page for a newly uploaded trial (using the excel upload), the 'Working...' dialog displays and does not go away and the field layout is not displayed.

This warning is displayed in the JS console (the iterator warning pops up right after expanding the Field Layout Map section):
![Screen Shot 2022-02-18 at 11 40 35 AM](https://user-images.githubusercontent.com/7526014/154726946-59b06ef9-5689-4cbf-b310-0169d58d5079.png)

The AJAX requests succeed, however the `/observationunits` call returns an empty `data` array:
![Screen Shot 2022-02-18 at 11 41 26 AM](https://user-images.githubusercontent.com/7526014/154727066-0df02069-4314-4b5c-8e3e-c291c432da03.png)

The problem is fixed after doing a manual refresh from the Search Wizard.  So, it seems like something is not being refreshed after new trials are loaded.

For Bugs:
---------

**Comment by bellerbrock** [comment]
Naftali and I were looking at this a few weeks ago. From what we saw the materialized view refresh is triggered at the end of the upload, it just takes a while to complete. Would be good to confirm that though.

If that is what's happening the best solution may be to modify the layout retrieval so that it defaults to a slower 'Native' search if the materialized view search returns nothing.

**Comment by lukasmueller** [comment]
Did you use the multi trial upload? Discovered that the multi trial upload does not update the materialized_phenotype_json_table view, which is needed for that feature. See duplicate ticket #3969.
