### ISSUE TITLE
Large label set not splitting into batches for download

### ISSUE THREAD

**Issue by tphickey** [solgenomics/sgn#4082]
Expected Behavior 
--------------------------------------------------------------------------

Clicked "Download zpl file" and nothing happened. Note on page reads, "If you are trying to download a very large set, you will be given the option to download your labels in batches." I was not given the option to download in batches. 

For Bugs:
---------

### Environment 

Last page of Label Designer walkthrough.

#### Steps to Reproduce

Created a list of 1000 list items (1-1000). Added 3 elements of text, one of which was the list item name.

**Comment by tphickey** [comment]
We are running a Breedbase instance modeled after Cassavabase. The list contents were the numbers 1-1000. The three texts elements added were “Arl2022”, “HempGWAS” and the list_item_name (1-1000). I didn’t use an incrementing number to get the 1-1000. This list is not associated with any trial or plot in the database.

**Comment by bellerbrock** [comment]
Hi @tphickey, thanks for the additional details and sorry for the delay.

It turns out this was a simple error restricted to downloads of exactly 1000 labels. I've just pushed a fix and made a pull request, for a solution in the meantime you can add one extra item to your list to bump it up to 1001 :laughing:
