### ISSUE TITLE
Remove Chado repo from docker

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4259]
Expected Behavior 
--------------------------------------------------------------------------
Remove Chado repo from docker (leave chado_tools repo there) and verify if chado_tools/chado/lib is in the path in the docker

For Bugs:
---------

**Comment by dwaring87** [comment]
One thing I noticed when updating the chado repo in our Docker is to update the [`PERL5LIB` path in the Dockerfile](https://github.com/solgenomics/breedbase_dockerfile/blob/ec554a91ad8bb65ecaeb9f22ff6ed0c77e6d6e39/Dockerfile#L148) to use the chado_tools directory (otherwise the ontology loading script won't find the Chado libs).

**Comment by lukasmueller** [comment]
Done.
