### ISSUE TITLE
Wizard VCF download broken

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#4267]
fatal error when downloading genotype data from wizard

error] Attribute (protocol_id_list) does not pass the type constraint because: Validation failed for 'ArrayRef[Int]|Undef' with value [ undef ] at /home/production/cxgn/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Object.pm line 24
	Moose::Object::new('CXGN::Genotype::Download::VCF', 'HASH(0x5557750b6ec0)') called at lib/CXGN/Genotype/DownloadFactory.pm line 56

**Comment by lukasmueller** [comment]
I think you need to set the default protocol for genotyping in sgn_local.conf

________________________________
From: The Triticeae Toolbox ***@***.***>
Sent: Thursday, October 27, 2022 8:38 AM
To: solgenomics/sgn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [solgenomics/sgn] Wizard VCF download broken (Issue #4267)


fatal error when downloading genotype data from wizard

error] Attribute (protocol_id_list) does not pass the type constraint because: Validation failed for 'ArrayRef[Int]|Undef' with value [ undef ] at /home/production/cxgn/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Object.pm line 24
Moose::Object::new('CXGN::Genotype::Download::VCF', 'HASH(0x5557750b6ec0)') called at lib/CXGN/Genotype/DownloadFactory.pm line 56

**Comment by ClayBirkett** [comment]
All the other pages pickup the default genotype protocol okay. The docker image is using Perl v5.32.1, could that be a problem?

**Comment by isaak** [comment]
Fixed: #4269
