### ISSUE TITLE
Field Layout Tools and Phenotype Heatmap caught in endless loop

### ISSUE THREAD

**Issue by tphickey** [solgenomics/sgn#4276]
Expected Behavior 
--------------------------------------------------------------------------
On a trial page, expanding a field layout caught in endless "Working" loop. Suspicion is that trial upload row_number did not start with 1. Reason for not starting at row 1 is that this space contains two trials and second trial started further into the high tunnel space.

For Bugs:
---------

### Environment 
Trial page while expanding Field Layout Tools and Phenotype Heatmap subsection.

#### Steps to Reproduce
Upload a trial that doesn't start with row 1. Maps used to display before new feature updates such as inverting rows, adding borders, and more.

**Comment by tphickey** [comment]
@dwaring87 My last update might have been just before this update. My latest update included the features I mentioned. How would I check which version I have?

**Comment by darekbienkowski** [comment]
@tphickey 
We think that problem was resolved with the last commits/pull described by @dwaring87.
Can you check which version of the SGN repository you use in your system, something like it sgn folder:

`git describe`

or which docker version of the image ( TAG ) - if your system is docker based by command :

`docker image ls `

or if you have TAG "latest," - the full TAG number can be checked like that:

`docker image ls`                         # take IMAGE ID and then 
`docker image inspect <IMAGE ID> | grep image.version`

Also, can you provide us with more information about your system? 
What kind of database or server do you work with?

**Comment by lukasmueller** [comment]
I will generate a new docker image and upgrade the system that Thomas is using.

cheers
Lukas

________________________________
