### ISSUE TITLE
Wizard phenotype download crashes

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4344]
Expected Behavior 
--------------------------------------------------------------------------
As reported by Adam Famoso and Lizbeth Pino Duran reported a similar issue.

For Bugs:
---------

**Comment by bellerbrock** [comment]
The error in LSU ricebase appears to be fixed, we were unable to reproduce it after the docker image was updated and dbpatches were run.

The cassavabase error is likely caused by outdated materialized views. Manual refreshes are running with 3/4 completed. But the fact that they hadn't refreshed in over a month is concerning. We need to do more materialized view refactoring.

**Comment by lukasmueller** [comment]
#4352
