### ISSUE TITLE
error downloading genotyping data from the wizard in cassavabase (live site)

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#441]
When downloading genotypic data using th ewizard an server error is displayed and access.log shows:

 Caught exception in SGN::Controller::BreedersToolbox::Download->download_gbs_action "JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at lib/SGN/Controller/BreedersToolbox/Download.pm line 500."

**Comment by bellerbrock** [comment]
this was affecting the genotype downloads with the new protocol because we weren't filtering by type_id and were catching igd_numbers in the genotypeprop table as well as the actual genotypes. fixed by 	352a2cd7b10df5fb36776e6d30abe7e3aadd70dc in topic/fix_geno_download, which now has a bunch of additional fixes and optimizations. ready to pull
