### ISSUE TITLE
Trait properties and scale aren't loaded

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4429]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by chris263** [comment]
Trait properties and scale are not showing up in Sempre Breedbase.

The expected information is the as available on: https://cropontology.org/term/CO_322:0000781 

<img width="1246" alt="Screenshot 2023-02-08 at 9 55 55 AM" src="https://user-images.githubusercontent.com/51970212/217536491-3a9c9584-29b2-4467-8150-75e6a83e3a45.png">

**Comment by nmenda** [comment]
@chris263 breedbase stores only traits/variables.
The scale and method is an integral part of the variable, and breedbase does not allow composing traits with trait+scale+variable like other databases allow. 

We can discuss storing scales and methods as well, but that requires first some cleaning up since most ontologies have redundant scale and method terms, re-used names, etc. so those are not compatible with the breedbase schema. 

In the example trait from maiz, ideally the trait name should be human-readable and have a definition that describes the method and scale used to measure it. 
The acronym is usually stored as a trait synonym.

**Comment by chris263** [comment]
Hi Naama,

Thanks for the message. Do you have a moment today for a short conversation?

Cheers,
Chris

On Feb 14, 2023, at 1:15 PM, Naama Menda ***@***.***> wrote:



@chris263<https://github.com/chris263> breedbase stores only traits/variables.
The scale and method is an integral part of the variable, and breedbase does not allow composing traits with trait+scale+variable like other databases allow.

We can discuss storing scales and methods as well, but that requires first some cleaning up since most ontologies have redundant scale and method terms, re-used names, etc. so those are not compatible with the breedbase schema.

In the example trait from maiz, ideally the trait name should be human-readable and have a definition that describes the method and scale used to measure it.
The acronym is usually stored as a trait synonym.

**Comment by nmenda** [comment]
@chris263 let's continue this on slack
