### ISSUE TITLE
Simplifying Cross Upload

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#4516]
I don't understand why there are three upload formats for crosses.

![Screenshot from 2023-04-26 16-55-13](https://user-images.githubusercontent.com/36375878/234702027-d5012adf-fd1f-45e7-8150-21f6a14fa7b1.png)

Wouldn't it be easier to have more general female and male cross unit columns, which can be either an accession name, a plot ID, or plant ID? Like the Intercross upload. Also why is it required to provide the female and male accession name in addition to the female and male plot/plant ID? If the plot or plant ID is provided, shouldn't Breedbase know the source accession of the plant/plot? It is a burden to have to look up the accession name if a plot or a plant ID was used as the cross unit.

**Comment by ch728** [comment]
Another issue is in some cases I know the specific plant that was used for a parent but may have a plot or accession for the other parent. There is no way to mix and match all possible cross units with the current format.

**Comment by titima15** [comment]
@ch728 cross upload is an old feature, mainly for uploading historical data. The main purpose for having female and male accessions included in the spreadsheet is for users (technicians) know what are the parents of those crosses (human perception). In their spreadsheet, they always have female and male accessions information.

Most users record only one type of stocks (either plot or plant level). That's why we separate the two formats.

Intercross is a new feature that we try to streamline the process, that's why I implemented it that way.

Definitely I can modify cross upload to have only one format similar to intercross upload, if our group think that it should be that way.

**Comment by titima15** [comment]
@ch728 I will add another file format similar to Intercross upload.

**Comment by titima15** [comment]
Done via 4365be6 @ch728 you will see additional dropdown option for this upload
