### ISSUE TITLE
make "accession" the default stock type in stock search

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4537]
Expected Behavior 
--------------------------------------------------------------------------
the drop down is empty now, searching everything - very slow. 

For Bugs:
---------

**Comment by darekbienkowski** [comment]
A problem is that removing the "Accession" selection from the dropdown is intentional. 
In a code, all dropdowns are reset. This means on purpose value is changed from "Accession" to empty... 
The question is what should be the default behavior of that dropdown and search functionality?

https://github.com/solgenomics/sgn/blob/42b7b1851c1575ed47f2f0ef22ac8039b989f1f6/mason/search/stocks.mas#L328

**Comment by lukasmueller** [comment]
I think the default should be accession

________________________________

**Comment by darekbienkowski** [comment]
https://github.com/solgenomics/sgn/pull/4541#issue-1717332819
