### ISSUE TITLE
 Change the download option in the wizard to require login

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#473]
Also, write the user info to the corresponding disk file to keep track of the download.

**Comment by bellerbrock** [comment]
Logins are now required. Trial phenotype downloads are being logged, with username, time stamp, and trial id to `$c->config->{trial_download_logfile}` . For the cassava production and test sites the path is /export/prod/logs/cassava_trial_download_log.

For the time being at least, genotypes downloads aren't being logged. Perhaps they should be?

**Comment by isaak** [comment]
Hi Bryan,

Another place you can save the log file is in a site specific folder (eg. /export/prod/tmp/cassavabase.org/): https://github.com/solgenomics/sgn/blob/master/lib/SGN/Role/Site/Files.pm#L338.   I think this way you will know what is downloaded from which site.... the downside, perhaps, you will lose control of the log history, since this dir gets cleaned up. 

Nick and I are creating site specific folders in the /export/prod/tmp/ to save files.

**Comment by bellerbrock** [comment]
Ok, thanks for the heads up Isaak! That's the path stored in the `tempfiles_base` conf variable, right? How often is the tmp dir cleaned up?

If tmp gets cleaned up too often, I suppose I could also just change the `trial_download_logfile` in cassava-test's sgn_local.conf file. to something like /export/prod/logs/cassava-test_trial_download_log. It is definitely confusing that the test and live site are logging to the same file right now.

**Comment by isaak** [comment]
$c->site_cluster_shared_dir would create subfolder with the hostname  in the cluster_shared_tempdir not in the tempfiles_base. 

tempfiles_base is cleaned up on server start up. cluster_shared_tempdir is cleaned up on need basis. I clean up the the solgs subdirs generally when new genotype data sets are loaded to the dbs or when debugging...

Have you considered storing the download history in the db?
