### ISSUE TITLE
Add drop down menu for species in dialog box  selection while adding a new accession. 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#501]

**Comment by nickmorales** [comment]
29cddef2494ee9d160e3663f93995e476c8789ea

**Comment by nickmorales** [comment]
that commit fixes the autocomplete dropdown, but maybe you meant something else...

**Comment by bellerbrock** [comment]
Sounds like the same issue, just a coincidence it was getting fixed in a different commit at about the same time. We noticed it here in Ghana, but I think it was also raised at the yambase workshop. Let me know if I'm wrong.

Oh, and we also noticed conf variables for the default/preferred species name weren't set for most databases. I've set them for sp, cassava, and yam, but wasn't sure what to do for musa. Guillaume, any thoughts? https://github.com/solgenomics/sgn/issues/494
