### ISSUE TITLE
Trial page PCA analysis not working, at least for some trials

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#507]
Reported by Simon at CRI in Ghana:
Hi guys, I have a challenge running the trial correlation and PCA analysis. Any advice for me?

I just tested the tool in this trial http://sweetpotatobase-test.sgn.cornell.edu/breeders/trial/139?format= and it fails with the error message 'This population has no phenotype data.', despite 27 phenotyped traits.

**Comment by isaak** [comment]
This problem is specific to the SPTest site. Is torque working on the site? Below is the error message from the server:

submitting correlation job to the cluster..
CXGN::Tools::Run error running `qsub`: qsub: Bad UID for job execution MSG=ruserok failed validating www-data/www-data from sweetpotatobase-test.sgn.cornell.edu

It is also using old R version (2.15) instead of version > 3.  https://github.com/solgenomics/sgn/issues/235

**Comment by lukasmueller** [comment]
Fixed torque on sweetpotatobase and sweetpotatobase-test.
