### ISSUE TITLE
Add traits to inventory.breedbase

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#5142]
Expected Behavior 
--------------------------------------------------------------------------
Could you please add the following ontology to inventory.breedbase? I think it is formatted correctly, but let me know. 

Thanks!

[NCGRCD_new.txt](https://github.com/user-attachments/files/17272399/NCGRCD_new.txt)

For Bugs:
---------

**Comment by lukasmueller** [comment]
Can we briefly talk about  the ontology? I will be back in Ithaca on Thursday.


cheers
Lukas





________________________________
From: Heather Manching ***@***.***>
Sent: Sunday, October 6, 2024 11:27 PM
To: solgenomics/sgn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [solgenomics/sgn] Add traits to inventory.breedbase (Issue #5142)


Expected Behavior

Could you please add the following ontology to inventory.breedbase? I think it is formatted correctly, but let me know.

Thanks!

NCGRCD_new.txt<https://github.com/user-attachments/files/17272399/NCGRCD_new.txt>

For Bugs:
Environment
Steps to Reproduce

**Comment by hkmanching** [comment]
Sure! I am out this week at IPPS, but I can meet on Tuesday at 11?

**Comment by lukasmueller** [comment]
Tuesday at 11 is ok :-)  - Can you still make it?

**Comment by hkmanching** [comment]
Yes. Lab meeting link?

**Comment by lukasmueller** [comment]
Yes

**Comment by hkmanching** [comment]
I sent the link to the drive file, but including here as well. 
[InventoryBase_Ontology_20241015.xlsx](https://github.com/user-attachments/files/17415469/InventoryBase_Ontology_20241015.xlsx)

**Comment by lukasmueller** [comment]
I added the synonym and variable name as discussed, please check.
