### ISSUE TITLE
Getting error pop-up on multiple windows in Inventory BB. 

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#5173]
Expected Behavior 
--------------------------------------------------------------------------

Not sure what the error is, but this keeps popping up. 

For Bugs:
<img width="1460" alt="Screenshot 2024-10-30 at 10 41 50 AM" src="https://github.com/user-attachments/assets/e4525cff-a094-4541-b3f6-48b40486083e">

---------

**Comment by lukasmueller** [comment]
Is this on inventory.breedbase.org?

cheers
Lukas
________________________________
From: Heather Manching ***@***.***>
Sent: Wednesday, October 30, 2024 10:43 AM
To: solgenomics/sgn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [solgenomics/sgn] Getting error pop-up on multiple windows in Inventory BB. (Issue #5173)


Expected Behavior

Not sure what the error is, but this keeps popping up.

For Bugs:
Screenshot.2024-10-30.at.10.41.50.AM.png (view on web)<https://github.com/user-attachments/assets/e4525cff-a094-4541-b3f6-48b40486083e>

________________________________
Environment
Steps to Reproduce

**Comment by hkmanching** [comment]
Yes.

**Comment by lukasmueller** [comment]
Thanks for the confirmation. The issue should be fixed. When loading the new cv, a new term VARIABLE_OF was loaded, which was now present twice. The one associated with the cassava ontology was renamed.
