### ISSUE TITLE
manage -> accessions page is extremely slow to load

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#557]
The section that lists the populations seems the culprit. It could be moved to a separate page linked from the accession page, or it should be changed to an ajax-based section.

**Comment by bellerbrock** [comment]
Is this the issue that was being caused on cassavabase by the large
populations loading in the populations section? Something that could be
fixed by making the population section collapsed by default and and just
loading it on demand with an ajax request?

On 17 June 2016 at 10:33, Lukas Mueller <notifications@github.com> wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solgenomics/sgn/issues/557>, or mute the thread
> <https://github.com/notifications/unsubscribe/AKxiQll7uByhARTMp0xvUYhlwBZerjPPks5qMrAdgaJpZM4I4arc>
> .
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868

**Comment by lukasmueller** [comment]
Yes, that’s what needs to be done… or factor it out to a separate page.

Do you want to take this one?

Lukas

**Comment by bellerbrock** [comment]
No problem, I'll take this one
