### ISSUE TITLE
How to handle stock names with special characters?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#631]
In musabase stock table, accession such as as "Hartón Maqueo " or " Figue Pomme Géante "
display typos in search outputs due to accents: "Figue Pomme GÃ©ante", "HartÃ³n Maqueo"
Seems that Postgres  may not handle all special characters: https://www.postgresql.org/docs/9.0/static/multibyte.html  and may need to be truncated.
Cross reference can be found correctly typed in other DBs, ex:
https://www.crop-diversity.org/mgis/accession-search?accession_name=&accession_numbers=ITC0628

**Comment by nickmorales** [comment]
this is strange because it does display correctly in some places e.g. https://musabase.org/stock/40489/view

**Comment by lukasmueller** [comment]
This has to do with Unicode encoding. The database should be in unicode, meaning it can display all the different characters (even Kanji and Chinese etc). If it doesn’t display correctly in the terminal, it is because the terminal is set to ASCII. The webpage may or may not display it correctly, Perl (and particularly mason) has some trouble with Unicode.

cheers
Lukas

**Comment by bauchetg** [comment]
This is still a problem, specifically for the West African program:
ex: 
![screen shot 2018-11-01 at 9 34 12 am](https://user-images.githubusercontent.com/12039071/48318655-29c78780-e604-11e8-8d5e-b46eb7dafcb3.png)
obino l'ewai

**Comment by lukasmueller** [comment]
Mason encoding was fixed by adding 
SGN/View/Mason.pm
27:        preamble => "use utf8; ",

**Comment by lukasmueller** [comment]
This was fixed in the topic/fix_ajax_encoding branch

**Comment by lukasmueller** [comment]
This should be fixed.
