### ISSUE TITLE
Wizard and single accession search do not output the same number of related trials

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#700]
Think it was pointed out earlier but cant find the related issue. Ex: TME1 (=Antiota) gives 196 associated trials in the stock search but 205 using the wizard search using "test_antiota" public list

**Comment by bauchetg** [comment]
probably to do with conflicts between stock_name and uniquename?

**Comment by lukasmueller** [comment]
One search may count folders and other objects in the project table, where the other search does it correctly (not sure which one...)

**Comment by bellerbrock** [comment]
Thanks for the example Guillaume. I assume by stock search you mean the trials section on the stock page? It looks like counting of folders or other project table entries is not the issue. The discrepancy is due to the stock page using the get_trials method in cxgn-corelibs/lib/CXGN/Chado/Stock.pm, which in turn uses SQL that requires nd_geolocation to be defined.

For example, TMEB1 is used in both trial [12localgermUB](https://cassavabase.org/breeders/trial/454?format=) and trial [12localgermIB](https://cassavabase.org/breeders/trial/545?format=). 12localgermUB shows up in both searches, but 12localgermIB shows up only in the wizard search results. Its missing from the trials section on the [TMEB1](https://cassavabase.org/stock/39629/view) stock page because it doesn't have a location stored.

I guess the solution here is to either change the SQL used by the get_trials method in cxgn-corelibs/lib/CXGN/Chado/Stock.pm, or change the stock page to simply use the same method as the wizard. Any thoughts on what'd be best?

And I suppose we should also go and store locations for all the trials where they're missing, but obvious from the name or description. 12localgermIB has got to be Ibadan.

**Comment by lukasmueller** [comment]
Looks like that SQL should probably just have a left join to the location…
I think in cases where we don’t need absolute speed we should not use the materialized views, so this one we could just modify the SQL.

cheers
Lukas

**Comment by bauchetg** [comment]
Hi Bryan, yes I mean that trial section on the stock page. When looking at the wizard and select the "     " default location: 67 trials all from CIAT. 
Similarly, when using the Trial search, I find these 67 trials and 163 others with unassigned locations as well as the main folders of Breeding programs (ex: "Rayong")

**Comment by bellerbrock** [comment]
Ok, I went ahead and modified the query. It was already using a LEFT JOIN to projectprop, but moving `projectprop.type_id=$geolocation_type_id` from the where clause to the join condition did the trick. This strategy might be useful where other missing props are giving us trouble, in conjunction with other fixes. Closed with in cxgn-corelibs with 7c13333d97f3481cd725a84aeb747997af7198c3
