### ISSUE TITLE
fast phenotype downloads doenst always give output

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#815]
From Prasad:
The Wizard fast download gives empty output with some trials:
15geneticgainIB (Augmented)
But works fine with other
15ayt10yrtIB (RCBD)
As well, the "fast" option (plot only) is clear but "complete" is less (maybe specify "plot and plant based data"?)

**Comment by bellerbrock** [comment]
Hi @bauchetg and @pvnsprasad,

Thanks for the examples, I just took a look at them and I see what is going on. If you hover over the fast or complete options and read the tooltips that may help make the distinction clearer.

The fast option is fast because it uses the materialized views, which are a form of caching. It may miss recently uploaded data that has not yet been cached. That is the case here with the phenotypes for the 15geneticgainIB trial.

To prevent this problem, at the end of a data upload a submitter can click "refresh materialized views" in the last upload dialog; this will rebuild the views so that they include the new data. Or, from the wizard, a submitter can click the 'Update Wizard' in the top righthand corner. The dialog that opens will tell them when an update was last completed, and if they are looking for data that has been loaded more recently they can initiate a new update.

I hope that helps! The last update was Jan 6th, so I just initiated a new one. We can also modify the download dialog to make this more clear.

**Comment by lukasmueller** [comment]
Implement a cronjob that updates the materialized views every night. Update materialized views after trial upload.

**Comment by lukasmueller** [comment]
Another possibility is to keep track of when (and by whom, etc) a particular trial was modified last, and check that against the last modification time of the materialized views. (Maybe complicated when queries span a lot of trials and don't actually join to them).

**Comment by bauchetg** [comment]
implemented
