### ISSUE TITLE
create dataset from wizard

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#866]

**Comment by lukasmueller** [comment]
this is addressed in the branch topic/dataset

**Comment by lukasmueller** [comment]
Instead of having a separate entry in the toolbar, the datasets could simply list the stored datasets on the wizard page directly, in the "Store Dataset for selected data" section... Feedback welcome.
The latter should be renamed to "Store current selection" or something similar?

Bryan - I couldn't find how to replay the selections on the wizard... How is that done?
