### ISSUE TITLE
New cassava flowering ontolgy terms: new variables or postcomposing?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#950]
@nmenda @aafolabi @nickmorales @bellerbrock 
Cassava flowering experiments use trait similar to the postcomposed traits in Cassbase
requiring new ontology variables, including:
"levels" = branching level = branching number of the fork from the ground level to the top (from 1 to 10)
and some new traits:
- grafting method: whip, wedge and control (we can request method description)
- different time scela: 3 weeks or 6 weeks and control. As well: 4,5,6,7,8,9,10 months after planting (MAP)
- different temperatures: 28°C and 40°C
- different hormonal treatments (hormone types and concentration in PPM):
See enclosed spreasheet: 
[hormonal_treatments.xlsx](https://github.com/solgenomics/sgn/files/902965/hormonal_treatments.xlsx)

-- suggestion: In Cbase factors set by default are rep, clone and bulk, "treatment" does not exist yet particular ontology terms could be tagged as "treatment/factor" so thatr they could specified as such when doing analysis, notably regarding future split plot design/factorial analysis.

related to: #889 #888 and #860

**Comment by nickmorales** [comment]
In cassbase we are postcomposing CO terms with plant age (number of weeks) from CASSTIME and the institute that took the measurement CASSINST.

For cassbase, factors like tissue and unit need to be part of the CO term.

**Comment by bellerbrock** [comment]
Hi @bauchetg, thanks for bringing these up. Like Nick said, it should be straightforward to handle the different time scales with postcomposing.

The others, I'd agree, are different. Graft type, temp, and hormone aren't really traits, they're additional independent or manipulated variables in the experiment. As such, maybe we could incorporate them into a a new 'treatment' ontology? Then, instead of combining them into traits, treatment ontology terms could be used in the trial design as additional factors beyond genotype. I guess there isn't support for that yet, but should be when we add split plot design. And in the meantime, maybe we should we add something like a 'Flowering experiment' trial type?

**Comment by bauchetg** [comment]
-1- New cvterms to be loaded:
As experiment variables: temperature (28 and 40) and hormone treatments 
As Stock prop: "graft" stock_relationship: "scion_of" or "rootstock_of" see #949 
As Stock prop: "grafting method": whip, wedge and control

-2- New cassava ontology terms:  
New term for nodes: "Nodes to branching"  = "Average number nodes per branch level":
counting all nodes per each level (if  on a plant at harvest  on each level (if more then 1 branch, one selected, up  to the apical shoot), value averaged per plot.
 Check: Add "Average number nodes per branch level" issue for more details:
https://github.com/solgenomics/cassava/issues/15

-3- New terms that can be covered using existing terms: 
-1- new trait time can be postcomposed using existing time ontology in month (https://github.com/solgenomics/sgn/blob/master/ontology/cxgn_time.obo) 
-2- terms including "level" information (ex: "branching level"),  can entered in combination of this term: CO:0000079 'branching level counting'  (	Count the number of levels of branching at harvest
).
